version: 0.2

phases:
  pre_build:
    commands:
      - echo "Cleaning up old container..."
      - docker rm -f my-app-container 2>/dev/null || true
      - echo "Downloading Secrets.java from S3..."
      - aws s3 cp s3://codepipelinestartertempla-codepipelineartifactsbuc-bd73oogfwokp/Secrets.java src/main/java/org/ilghar/Secrets.java
      - echo "Verifying Secrets.java existence..."
      - ls -l src/main/java/org/ilghar/
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-app:latest .
  post_build:
    commands:
      - echo "Running the Docker container..."
      - docker run -p 8443:8443 --name my-app-container my-app:latest

artifacts:
  files:
    - "**/*"