version: 0.2

phases:
  pre_build:
    commands:
      - echo "Cleaning up old container..."
      - docker rm -f my-app-container 2>/dev/null || true
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-app:latest .
  post_build:
    commands:
      - echo "Running the Docker container..."
      - docker run -p 8443:8443 --name my-app-container my-app:latest

artifacts:
  files:
    - "**/*"